### ISSUE TITLE
Exponentially delay polling of queue that had no elements

### ISSUE THREAD

**Issue by ixti** [sensortower/sidekiq-ultimate#1]
Right now if polling queue gave no result we "pause" polling that queue on sidekiq process for 4 seconds (2*TIMEOUT) - that should be dynamically growing:

1 time returned nothing = skip for 2 seconds
2 times returned nothing = skip for 4 seconds
3 times returned nothing = skip for 6 seconds
4 times returned nothing = skip for 8 seconds
5+ times returned nothing = skip for 10 seconds

**Comment by sensorsasha** [comment]
Global queue pausing on exhaustion was implemented in https://github.com/sensortower/sidekiq-ultimate/pull/5
